PlayMode fix
bedrock-crustaceans/bedrockrs pull request #47
Opened 2024-08-20 12:05 UTC by ismaileke

Is it right to use `clone()`? I would appreciate if you could review the changes.

2024-08-20 12:10 UTC, ismaileke commented
```rust
let _vr_gaze_direction = ProtoCodec::proto_deserialize(stream)?;
or
let _vr_gaze_direction = Vec3::<LE<f32>>::proto_deserialize(stream)?;
```
I think the second one is right

2024-08-22 16:18 UTC, theaddonn requested changes

2024-08-22 16:18 UTC, theaddonn commented on crates/proto/src/packets/player_auth_input.rs
> -            4 => {
I do think that it is better to store the vr_gaze_direction in the enum

2024-08-22 16:18 UTC, theaddonn commented on crates/proto/src/packets/player_auth_input.rs
> +            // Maybe we can save it in a struct, I don't know
it would be best to save it into the enum, like it was done previously

2024-08-22 16:18 UTC, theaddonn commented on crates/proto/src/types/play_mode.rs
> -    Reality(Vec3<LE<f32>>),
here, thats how we've done it in the past

2024-08-24 05:46 UTC, theaddonn commented
looks all good!

2024-08-24 05:46 UTC, merged