impl enums for v662
bedrock-crustaceans/bedrockrs pull request #68
Opened 2024-11-21 13:47 UTC by OmniacDev

2024-11-21 14:24 UTC, theaddonn commented
Something I noticed in general is that you are creating a new module/namespace quite often, that is unnecessary..
for example `actor_block_sync_message::ActorBlockSyncMessage::MessageId` gets quite long, Rust already creates a new module for every file, so you might want to remove the additional module in the file and rename the internal enum to something like `ActorBlockSyncMessageId`

2024-11-21 15:32 UTC, theaddonn commented
Also, it is not that important to match Mojang's names 1:1 since they can be quite confusing at times

2024-11-21 16:10 UTC, theaddonn requested changes
So urm, this review got quite big....

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/actor_block_sync_message.rs
> +pub mod ActorBlockSyncMessage {
No need for the additional `mod`, you can just rename the type to `ActorBlockSyncMessageId` :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/animate_packet.rs
> +pub mod AnimatePacket {
No need for the additional `mod`, you can just rename the type to `AnimateAction` :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/animate_packet.rs
> +pub mod AnimatePacket {
Also, it is confusing when you add an extra `packet` in the file name, maybe change it to `crates/proto/src/version/v662/enums/animate.rs`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/build_platform.rs
> +    Sony = 11,
Add some cool doc comment (Aka, just a comment using triple backslashes) that this means PlayStation, thanks :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/build_platform.rs
> +    Nx = 12,
Add some cool doc comment that this means Nintendo Switch, thanks :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/camera_preset.rs
> +pub mod CameraPreset {
No need for the additional `mod`, you can just rename the type to `CameraPresetAudioListener` :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/animation_mode.rs
> +pub enum AnimationMode {
Do you think it makes sense to move this enum into the `enums/animation.rs` file as well?

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/build_platform.rs
> +    TvOsDeprecated = 10,
It may make sense to change this to just `TvOs` and add a `#[deprecated]` flag

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/clientbound_debug_renderer_packet.rs
> +pub mod ClientboundDebugRendererPacket {
No need for the additional `mod`, you can just rename the type to `ClientboundDebugRendererType` :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/clientbound_debug_renderer_packet.rs
> +pub mod ClientboundDebugRendererPacket {
It might also make sense to remove the `packet` in the file name, to avoid confusion...

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/clientbound_map_item_data_packet.rs
> +pub mod ClientboundMapItemDataPacket {
It might also make sense to remove the `packet` in the file name, to avoid confusion...

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/clientbound_map_item_data_packet.rs
> +pub mod ClientboundMapItemDataPacket {
No need for the additional `mod`, you can just rename the type to `ClientboundMapItemDataType` :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/code_builder_storage_query_options.rs
> +pub mod CodeBuilderStorageQueryOptions {
no need for the extra `mod` in general :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/complex_inventory_transaction.rs
> +pub mod ComplexInventoryTransaction {
It might make sense to rename this to `InventoryTransactionComplexType`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/connection.rs
> +pub mod Connection {
no need for the extra `mod` :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/container_enum_name.rs
> +pub enum ContainerEnumName {
Having the word `Enum` in both the type and file name seems a bit redundant

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/difficulty.rs
> +use bedrockrs_macros::ProtoCodec;
I think we actually already have that type in either `bedrockrs_shared` or `bedrockrs_core`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/emote_packet.rs
> +pub mod EmotePacket {
No need for the extra `mod` maybe just rename the type to `EmoteType` :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/emote_packet.rs
> +pub mod EmotePacket {
Also, it might get a little bit confusing if you have an additional `packet` in the file name

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/editor.rs
> +pub mod Editor {
Might make sense to remove the extra module and rename the type to `EditorWorldType`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/enchant.rs
> +pub mod Enchant {
Might make sense to rename the type to just `EnchantType` and avoid the extra module

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/game_type.rs
> +pub enum GameType {
I think we have this enum already in the `bedrockrs_core`/`bedrockrs_shared` crates, tho it seems like they are missing a bit. SO why not add the missing features there

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/minecraft_packet_ids.rs
> +pub enum MinecraftPackedIds {
I'm not sure if this enum is even used? I think we might be able to just ignore it...

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/inventory_source_type.rs
> +    NonImplementedFeatureTODO = 99999,
that seems questionable

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/game_rule.rs
> +pub mod GameRule {
You might just be able to eliminate the extra module and just call the type `GameRuleType`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/identity_definition.rs
> +pub mod IdentityDefinition {
You might just be able to not have the extra mod and just call the type `IdentityDefinitionType`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/interact_packet.rs
> +pub mod InteractPacket {
You might just be able to remove the extra mod and just call the type `InteractAction`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/interact_packet.rs
> +pub mod InteractPacket {
Also, having an additional `packet` in the file name migt get confusing

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/inventory_source.rs
> +pub mod InventorySource {
the extra mod is a bit unnecessary, just having the type be `InventorySourceFlags` is completely fine :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/item_descriptor.rs
> +pub mod ItemDescriptor {
no need for the extra mod, just call the type `ItemDescriptorType` :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/item_release_inventory_transaction.rs
> +pub mod ItemReleaseInventoryTransaction {
Unnecessary extra mod. just call the type `ItemReleaseInventoryTransactionType` :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/item_use_inventory_transaction.rs
> +    pub enum ActionType {
Unnecessary extra mod, just call the type `ItemUseInventoryTransactionType` :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/item_use_on_actor_inventory_transaction.rs
> +pub mod ItemUseOnActorInventoryTransaction {
Unnecessary extra mod, just call the type `ItemUseOnActorInventoryTransactionType` :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/lab_table_packet.rs
> +pub mod LabTablePacket {
Its better to remove the word `packet` in the file name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/legacy_telemetry_event_packet.rs
> +pub mod LegacyTelemetryEventPacket {
Its better to remove the word `packet` in the file name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/multiplayer_settings_packet_type.rs
> +pub enum MultiplayerSettingsPacketType {
Its better to remove the word `packet` in the file and type name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/player_list_packet_type.rs
> +pub enum PlayerListPacketType {
Its better to remove the word `packet` in the file and type name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/position_tracking_db_client_request_packet.rs
> +pub mod PositionTrackingDBClientRequestPacket {
Its better to remove the word `packet` in the file name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/position_tracking_db_server_broadcast_packet.rs
> +pub mod PositionTracingDBServerBroadcastPacket {
Its better to remove the word `packet` in the file name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/request_ability_packet.rs
> +pub mod RequestAbilityPacket {
Its better to remove the word `packet` in the file name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/score_packet_type.rs
> +pub enum ScorePacketType {
Its better to remove the word `packet` in the file and type name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/scoreboard_identity_packet_type.rs
> +pub enum ScoreboardIdentityPacketType {
Its better to remove the word `packet` in the file and type name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/set_title_packet.rs
> +pub mod SetTitlePacket {
Its better to remove the word `packet` in the file name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/set_title_packet.rs
> +pub mod SetTitlePacket {
Also, you can completely remove the extra mod, its not needed here :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/show_credits_packet.rs
> +pub mod ShowCreditsPacket {
You can just completely remove the extra mod here, it is not needed

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/sub_chunk_packet.rs
> +pub mod SubChunkPacket {
Its better to remove the word `packet` in the file name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/sub_chunk_packet.rs
> +pub mod SubChunkPacket {
You can also just remove the extra mod since it is just not needed

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/tag.rs
> +pub mod Tag {
You can just remove the extra mod and rename the enum to `TagType` :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/simple_event_packet.rs
> +pub mod SimpleEventPacket {
Its better to remove the word `packet` in the file name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/simple_event_packet.rs
> +pub mod SimpleEventPacket {
You can also remove the extra mod here to avoid confusion/problems, just rename the type to `SimpleEventType`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/serialized_abilities_data.rs
> +pub mod SerializedAbilitiesData {
This extra mod seems to be quite unnecessary, why don't you just call the type `SerializedAbilitiesData` and remove the extra module?

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/request_ability_packet.rs
> +pub mod RequestAbilityPacket {
You might also be able to remove the extra module and just call the type `RequestAbilityType`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/lab_table_packet.rs
> +pub mod LabTablePacket {
You should also be able to avoid the extra module and just call the enum `LabTableType`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/lab_table_reaction_type.rs
> +use bedrockrs_macros::ProtoCodec;
Why don't you merge both `lab_table_packet.rs` and `lab_table_reaction_type.rs` with both their enums into one single file, that is called something like `lab_table.rs`?

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/legacy_telemetry_event_packet.rs
> +pub mod LegacyTelemetryEventPacket {
You might be able to remove the extra mod and just rename the other enum from `Type` to `LegacyTelemetryEventType`. Also giving the `AgentResult` its own file might make sense

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/npc_dialogue_packet.rs
> +pub mod NpcDialoguePacket {
Its better to remove the word `packet` in the file name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/npc_request_packet.rs
> +pub mod NpcRequestPacket {
Its better to remove the word `packet` in the file name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/npc_request_packet.rs
> +pub mod NpcRequestPacket {
You might also be able to remove the extra mod, with just renaming the enum to `NpcRequestType`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/npc_dialogue_packet.rs
> +pub mod NpcDialoguePacket {
You might also be able to remove the extra mod, no need to rename the enum for this :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/npc_dialogue_packet.rs
> +pub mod NpcDialoguePacket {
Might also make sense to merge the contents of this file with the of the `crates/proto/src/version/v662/enums/npc_request_packet.rs` file, you might call it something like `npc.rs`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/persona.rs
> +pub mod persona {
You can just remove the extra module :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/player_auth_input_packet.rs
> +pub mod PlayerAuthInputPacket {
Its better to remove the word `packet` in the file name to avoid confusion

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/player_auth_input_packet.rs
> +pub mod PlayerAuthInputPacket {
You might also be able to remove the extra mod with just renaming the enum to `PlayerAuthInputData`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/player_position_mode_component.rs
> +pub mod PlayerPositionModeComponent {
Just remove the extra mod and call the file something like `position_mode`, thanks :)

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/level_event.rs
> +    ParticleLegacyEvent = 0x4000,
Can you like also convert this to a decimal number like the others are, instead of a hexadecimal one?

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/level_event.rs
> +    _9800 = 3617,
I will never understand Mojang...

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/map_decoration.rs
> +pub mod MapDecoration {
You might be able to avoid the extra mod here and just rename the enum to `MapDecorationType`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/map_item_tracked_actor.rs
> +pub mod MapItemTrackedActor {
You might be able to avoid the extra mod here and just rename the enum to `MapItemTrackedActorType`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/map_item_tracked_actor.rs
> +pub mod MapItemTrackedActor {
You also might be able to merge the contents of this file with the contents of `map_decoration.rs` to create some sort of `map.rs`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/position_tracking_db_client_request_packet.rs
> +pub mod PositionTrackingDBClientRequestPacket {
It might be a good idea to remove the extra mod and just call the enum `PositionTrackingDBClientRequestAction`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/position_tracking_db_server_broadcast_packet.rs
> +pub mod PositionTracingDBServerBroadcastPacket {
It might be a good idea to remove the extra mod and just call the enum `PositionTracingDBServerBroadcastAction`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/position_tracking_db_server_broadcast_packet.rs
> +pub mod PositionTracingDBServerBroadcastPacket {
It may make sense to also merge this with `position_tracking_db_client_request_packet.rs` into one file called `position_tracking_db.rs`

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/minecraft_eventing.rs
> +pub mod MinecraftEventing {
I don't even know what to say here, this is a true mess and idk what happened

Just maybe remove the extra mod and get each enum a separate file.. I guess

2024-11-21 16:10 UTC, theaddonn commented on crates/proto/src/version/v662/enums/puv.rs
> +pub mod Puv {
Seems like quite a lot of module nesting... why dont you just call the enum `LegacyLevelSoundEvent`.. adjust the file name and remove the other mods?

2024-11-21 22:21 UTC, OmniacDev commented
> Something I noticed in general is that you are creating a new module/namespace quite often, that is unnecessary..
> for example `actor_block_sync_message::ActorBlockSyncMessage::MessageId` gets quite long, Rust already creates a new module for every file, so you might want to remove the additional module in the file and rename the internal enum to something like `ActorBlockSyncMessageId`

Yeah this was sort of temporary until I can find the other stuff in the namespace, types& packets etc. I added comments in the mod.rs file for all the modules in there so I can easily go back and change them later

2024-11-21 23:23 UTC, OmniacDev commented
these workflows are annoying lmao, spamming my email every time I push

2024-11-22 01:59 UTC, OmniacDev commented
@theaddonn I might leave this as is for now, planning on coming back later after implementing all the types and packets to clean everything up.

2024-11-22 08:54 UTC, theaddonn commented
Sounds good!

2024-11-23 10:46 UTC, merged